In [7]:
import pandas as pd

file_paths = ['gap-test.tsv', 'gap-train.tsv', 'gap-validation.tsv']

dfs = []

for file_path in file_paths:
    df = pd.read_csv(file_path, sep='\t')
    dfs.append(df)
    
for i, df in enumerate(dfs):
    # Find the number of rows in the DataFrame
    num_rows = len(df)
    print(f"Number of rows in DataFrame {i+1}: {num_rows}")
    
concatenated_df = pd.concat(dfs)
concatenated_df

Number of rows in DataFrame 1: 2000
Number of rows in DataFrame 2: 2000
Number of rows in DataFrame 3: 454

,ID,Text,Pronoun,Pronoun-offset,A,A-offset,A-coref,B,B-offset,B-coref,URL
0,test-1,Upon their acceptance into the Kontinental Hoc...,His,383,Bob Suter,352,False,Dehner,366,True,http://en.wikipedia.org/wiki/Jeremy_Dehner
1,test-2,"Between the years 1979-1981, River won four lo...",him,430,Alonso,353,True,Alfredo Di St*fano,390,False,http://en.wikipedia.org/wiki/Norberto_Alonso
2,test-3,Though his emigration from the country has aff...,He,312,Ali Aladhadh,256,True,Saddam,295,False,http://en.wikipedia.org/wiki/Aladhadh
3,test-4,"At the trial, Pisciotta said: ``Those who have...",his,526,Alliata,377,False,Pisciotta,536,True,http://en.wikipedia.org/wiki/Gaspare_Pisciotta
4,test-5,It is about a pair of United States Navy shore...,his,406,Eddie,421,True,Rock Reilly,559,False,http://en.wikipedia.org/wiki/Chasers
...,...,...,...,...,...,...,...,...,...,...,...
449,validation-450,"He then agrees to name the gargoyle Goldie, af...",He,305,Lucien,252,False,Abel,264,False,http://en.wikipedia.org/wiki/Goldie_(DC_Comics)
450,validation-451,"Disgusted with the family's ``mendacity'', Bri...",she,365,Maggie,242,False,Mae,257,False,http://en.wikipedia.org/wiki/Cat_on_a_Hot_Tin_...
451,validation-452,She manipulates Michael into giving her custod...,she,306,Scarlett,255,False,Alice,291,True,http://en.wikipedia.org/wiki/Michael_Moon_(Eas...
452,validation-453,"On April 4, 1986, Donal Henahan wrote in the N...",her,330,Aida,250,False,Miss Millo,294,True,http://en.wikipedia.org/wiki/Aprile_Millo
453,validation-454,Pleasant explains Vassey's guilty conscience m...,him,282,Vassey,234,True,Denton,255,False,http://en.wikipedia.org/wiki/Small_Crimes

In [8]:
pronoun_counts = concatenated_df['Pronoun'].value_counts()
pronoun_counts

Pronoun
her     1232
his     1126
she      548
he       523
She      363
He       291
him      220
Her       83
His       67
hers       1
Name: count, dtype: int64

In [30]:
fem_df = concatenated_df[concatenated_df['Pronoun'].isin(['she', 'her', 'She', 'Her', 'hers'])]
masc_df = concatenated_df[concatenated_df['Pronoun'].isin(['his', 'he', 'He', 'him', 'His'])]

2227
2227
742
Length neutral: 1484

,ID,Text,Pronoun,Pronoun-offset,A,A-offset,A-coref,B,B-offset,B-coref,URL
0,test-94,He first performed with the MythBusters on Goo...,his,354,Vendera,200,True,Roger Schwenke,304,False,http://en.wikipedia.org/wiki/Jaime_Vendera
1,test-716,"As a young man, he gained preferment at Court ...",he,205,William,159,False,Henry,194,True,"http://en.wikipedia.org/wiki/William_Sandys,_1..."
2,development-1101,"Around the same time, and under the duo name o...",his,221,Mike Oldfield,237,False,Barry Palmer,252,True,http://en.wikipedia.org/wiki/Barry_Palmer_(Bri...
3,test-334,"After the war, Taylor returned to swimming. He...",He,274,Taylor,163,True,Matthew Webb,191,False,http://en.wikipedia.org/wiki/Henry_Taylor_(swi...
4,test-1115,Roy Martin Haines is a British historian. Hain...,his,189,Haines,42,True,George Martin,68,False,http://en.wikipedia.org/wiki/Roy_Martin_Haines
...,...,...,...,...,...,...,...,...,...,...,...
1479,test-553,Marshall is portrayed by Chadwick Boseman in a...,her,260,Vivien ``Buster'' Burey,221,True,Cecilia Suyat,305,False,http://en.wikipedia.org/wiki/Thurgood_Marshall
1480,development-328,After exposing Portia to outspoken Quest stude...,she,337,Virginia Woolf,249,False,Helen,280,True,http://en.wikipedia.org/wiki/Admission_(film)
1481,test-1842,"At WWE's Bad Blood PPV event on June 13, 2004,...",She,280,Kim,165,True,Stratus,271,False,http://en.wikipedia.org/wiki/Gail_Kim
1482,test-619,"Fullerton's book, Jane Austen and Crime (2004)...",her,146,Fullerton,0,False,Jane Austen,18,True,http://en.wikipedia.org/wiki/Susannah_Fullerton
1483,test-1620,"Austen's niece, Catherine Hubback, completed T...",her,279,Jane Austen,237,True,Edith,297,False,http://en.wikipedia.org/wiki/The_Watsons

In [38]:
# fem data 
# Randomly shuffle rows
fem_df_shuffled = fem_df.sample(frac=1, random_state=42) 

# Get the split point
fem_split_idx_1 = int(1/3 * len(fem_df_shuffled))

# Split the shuffled df
fem_df_1_3 = fem_df_shuffled.iloc[:fem_split_idx_1]
new_fem_df = fem_df_shuffled.iloc[fem_split_idx_1:]

print("1/3 of the rows:")
print(len(fem_df_1_3))
print("\n2/3 of the rows:")
print(len(new_fem_df))

1/3 of the rows:
742

2/3 of the rows:
1485

In [37]:
# masc data 
# Randomly shuffle rows
masc_df_shuffled = masc_df.sample(frac=1, random_state=42) 

# Get the split point
masc_split_idx_1 = int(1/3 * len(masc_df_shuffled))

# Split the shuffled df
masc_df_1_3 = masc_df_shuffled.iloc[:masc_split_idx_1]
new_masc_df = masc_df_shuffled.iloc[masc_split_idx_1:]

print("1/3 of the rows:")
print(len(masc_df_1_3))
print("\n2/3 of the rows:")
print(len(new_masc_df))

1/3 of the rows:
742

2/3 of the rows:
1485

In [42]:
gender_neut_df = pd.concat([fem_df_1_3, masc_df_1_3], axis=0)
# shuffle 
gender_neutral_df = gender_neut_df.sample(frac=1, random_state=42) 
print(len(gender_neutral_df))

1484

In [39]:
new_fem_df

,ID,Text,Pronoun,Pronoun-offset,A,A-offset,A-coref,B,B-offset,B-coref,URL
12,validation-13,"In the past,Princess Luminous is killed by Que...",her,345,Queen,312,True,Crystal,330,False,http://en.wikipedia.org/wiki/Futari_wa_Pretty_...
503,test-504,"Growing up in Indonesia, Wendy was ridiculed f...",She,354,Filipina,229,False,Tabusalla,271,True,http://en.wikipedia.org/wiki/List_of_Pinoy_Big...
727,development-728,And often (what) adds a tremendous amount of c...,She,373,Kate Flannery,238,True,Meredith Palmer,263,False,http://en.wikipedia.org/wiki/Product_Recall
860,test-861,At one stage Justice Barr counselled Blanchett...,she,342,Melinda Medich,260,True,Byrne,318,False,http://en.wikipedia.org/wiki/Death_of_Caroline...
1614,test-1615,Bao Yu overhears her and is moved. She teases ...,her,269,Jia,188,True,Granny,220,False,http://en.wikipedia.org/wiki/Dream_of_the_Red_...
...,...,...,...,...,...,...,...,...,...,...,...
1637,development-1638,Bryan has stated the goal of Paternity Court i...,her,351,Carole Lieberman,235,False,Lauren Lake,290,True,http://en.wikipedia.org/wiki/Lauren_Lake's_Pat...
232,development-233,Zane was born Elizabeth Frances Zane in Chicag...,Her,152,Elizabeth Frances Zane,14,True,Thalia,75,False,http://en.wikipedia.org/wiki/Lisa_Zane
314,development-315,Maria was born in Modena to Francesco I d'Este...,she,134,Maria,0,True,Maria Caterina Farnese,79,False,http://en.wikipedia.org/wiki/Maria_d'Este
760,development-761,"Ten seasons after they return to the Abbey, we...",her,362,Lonna,221,False,Martha,267,True,http://en.wikipedia.org/wiki/Loamhedge
1860,test-1861,"Columbia Pictures' Ship of Fools, also starrin...",She,309,Signoret,155,True,Lillian Hellman,175,False,http://en.wikipedia.org/wiki/Simone_Signoret

In [40]:
new_masc_df

,ID,Text,Pronoun,Pronoun-offset,A,A-offset,A-coref,B,B-offset,B-coref,URL
6,validation-7,Lieutenant General Weber Pasha wanted Faik Pas...,He,294,von Sanders,231,False,Faik Pasha,253,True,http://en.wikipedia.org/wiki/Faik_Pasha
244,test-245,The project was greenlit by Walt Disney Pictur...,he,291,Jeff Jensen,199,True,Lindelof,253,False,http://en.wikipedia.org/wiki/Tomorrowland_(film)
477,development-478,After successfully organizing the murder of th...,He,321,Roger de Flor,66,False,Michael IX,102,True,http://en.wikipedia.org/wiki/Michael_IX_Palaio...
405,test-406,"In 617, the secretary general of Wuyang Comman...",he,498,Yang,411,False,Wei,516,False,http://en.wikipedia.org/wiki/Wei_Zheng
902,test-903,Roosevelt also produced the film Pot o' Gold a...,his,353,Schenck,284,False,Roosevelt,327,True,http://en.wikipedia.org/wiki/James_Roosevelt
...,...,...,...,...,...,...,...,...,...,...,...
1031,development-1032,De Peyster was born in New Amsterdam on July 8...,his,288,Johannes de Peyster,160,True,David Provost,258,False,http://en.wikipedia.org/wiki/Abraham_de_Peyster
166,development-167,Geller is reckoned to have been among the best...,He,327,Geller,212,True,Mark Taimanov,280,False,http://en.wikipedia.org/wiki/Efim_Geller
219,development-220,Byas led a small group for several sessions fo...,his,272,Gillespie,203,False,Byas,296,True,http://en.wikipedia.org/wiki/Don_Byas
493,development-494,Candace once again avoids Phineas and Ferb's i...,he,311,Baljeet,205,False,Jeremy,292,True,http://en.wikipedia.org/wiki/Wizard_of_Odd
1295,test-1296,"He is married to the former Dorothy Mundy, who...",he,272,Doumar,216,True,Ronald Reagan,247,False,http://en.wikipedia.org/wiki/Robert_G._Doumar

In [43]:
gender_neutral_df

,ID,Text,Pronoun,Pronoun-offset,A,A-offset,A-coref,B,B-offset,B-coref,URL
1649,test-1650,She originally trained as an occupational ther...,her,426,Holly Kenyon,329,True,Jane Alison,401,False,http://en.wikipedia.org/wiki/Holly_Kenyon
175,test-176,"Since May 2011, she has written a biweekly col...",She,280,Postrel,198,True,Sally Satel,267,False,http://en.wikipedia.org/wiki/Virginia_Postrel
881,test-882,He advocated treating offenders like the menta...,his,338,Karl Menninger,349,True,Thomas Szasz,382,False,http://en.wikipedia.org/wiki/Karl_Menninger
278,development-279,"At age 17, Rinker moved to Seattle and worked ...",her,266,Rinker,205,False,Bailey,301,True,http://en.wikipedia.org/wiki/Mildred_Bailey
299,development-300,"He wintered in 1836-1837 at New Orleans, where...",he,323,Stewart,258,True,Alfred Jacob Miller,297,False,http://en.wikipedia.org/wiki/William_Drummond_...
...,...,...,...,...,...,...,...,...,...,...,...
633,development-634,The royalties from the performances of the wor...,his,310,Frankie Laine,277,False,Paul Weston,296,True,http://en.wikipedia.org/wiki/Jalousie_'Tango_T...
1512,test-1513,"According to the producer, Bieber suggested th...",he,228,Bieber,257,False,Boyd,272,False,http://en.wikipedia.org/wiki/Journals_(album)
377,test-378,"Dowd's impact on the careers of many esteemed,...",him,360,Bobby Darin,246,False,Eric Clapton,273,False,http://en.wikipedia.org/wiki/Tom_Dowd_and_the_...
376,test-377,The men's +80 kg competition in taekwondo at t...,he,287,*ngel Valodia Matos,182,True,Arman Chilmanov,264,False,http://en.wikipedia.org/wiki/Taekwondo_at_the_...
973,development-974,Although Arima and Kazuhide successfully retre...,his,300,Mino Akasaka,169,False,Sakon,199,True,http://en.wikipedia.org/wiki/Battle_of_Kuisegawa

In [45]:
gender_neutral_df.to_csv('gender_neutral_data.csv', sep='\t', index=False)

In [46]:
new_masc_df.to_csv('masc_data.csv', sep='\t', index=False)

In [47]:
new_fem_df.to_csv('fem_data.csv', sep='\t', index=False)