In [2]:
import pandas as pd

In [3]:
file_path = 'FEM_balanced_data2.csv'
df_fem = pd.read_csv(file_path)

In [4]:
test_size = int(len(df_fem) * 0.2)
df_test_fem = df_fem.iloc[:test_size]
df_train_fem = df_fem.iloc[test_size:]


df_test_fem.reset_index(drop=True, inplace=True)
df_train_fem.reset_index(drop=True, inplace=True)

print(len(df_train_fem))
df_train_fem.head()

1188

,ID,Text,Pronoun,Pronoun-offset,A,A-offset,A-coref,B,B-offset,B-coref,URL
0,development-1914,"Anne is able to convince the grandmother, a hy...",she,491,Anne,365,False,Katherine Brooke,416,True,http://en.wikipedia.org/wiki/Anne_of_Green_Gab...
1,test-1670,Bridget maintained correspondence throughout h...,her,313,Elizabeth,248,False,Bridget,271,True,http://en.wikipedia.org/wiki/Bridget_of_York
2,test-75,"In 1995 came the turn of playing Aurora, the c...",she,519,Valerie,357,False,Valeria,449,True,http://en.wikipedia.org/wiki/Valeria_Lynch
3,test-1723,The H*tel de Toulouse was the site of a scene ...,her,179,Sofia Coppola,51,True,Marie Antoinette,67,False,http://en.wikipedia.org/wiki/H%C3%B4tel_de_Tou...
4,test-1952,"During her time in the Papal States, she met P...",her,170,Violante Beatrice,192,True,Anna Maria,228,False,http://en.wikipedia.org/wiki/Duchess_Violante_...

In [5]:
file_path = 'NEUTRAL_balanced_data2.csv'
df_neutral = pd.read_csv(file_path)

In [6]:
test_size = int(len(df_neutral) * 0.2)
df_test_neu = df_neutral.iloc[:test_size]
df_train_neu = df_neutral.iloc[test_size:]


df_test_neu.reset_index(drop=True, inplace=True)
df_train_neu.reset_index(drop=True, inplace=True)

print(len(df_train_neu))
df_train_neu.head()

1188

,ID,Text,Pronoun,Pronoun-offset,A,A-offset,A-coref,B,B-offset,B-coref,URL
0,test-1181,Although this was during the height of the Lou...,their,283,Wright,318,True,Koziak,363,False,http://en.wikipedia.org/wiki/Edmonton-Strathco...
1,validation-336,Claire chooses between career and love when Ro...,them,310,Kristina,260,True,Claire,296,False,http://en.wikipedia.org/wiki/Claire_Walsh
2,test-1964,"The core of the band , called the X - Pensive ...",They,539,Sarah Dash,198,False,Patti Scialfa,265,False,http://en.wikipedia.org/wiki/Talk_Is_Cheap
3,development-1818,The independent spirit that governed Cox 's li...,their,257,Victoria Spivey,174,False,Cox,305,True,http://en.wikipedia.org/wiki/Ida_Cox
4,test-1963,Her Swiss mother Berta Passweg had lost her Sw...,they,321,Eva,256,False,Vera,264,False,http://en.wikipedia.org/wiki/Vera_Rottenberg_L...

In [7]:
file_path = 'MASC_balanced_data2.csv'
df_masc = pd.read_csv(file_path)

In [8]:
test_size = int(len(df_masc) * 0.2)
df_test_masc = df_masc.iloc[:test_size]
df_train_masc = df_masc.iloc[test_size:]


df_test_masc.reset_index(drop=True, inplace=True)
df_train_masc.reset_index(drop=True, inplace=True)

print(len(df_train_masc))
df_train_masc.head()

1188

,ID,Text,Pronoun,Pronoun-offset,A,A-offset,A-coref,B,B-offset,B-coref,URL
0,development-1500,As well as similarities as regards the type of...,his,399,Don Quixote,303,False,Cervantes,518,False,http://en.wikipedia.org/wiki/Corral_de_comedias
1,test-996,"Feeling guilty, no doubt, for having inherited...",He,400,Arthur Davies,251,True,John Frederick Mowbray-Clarke,323,False,http://en.wikipedia.org/wiki/Madge_Jenison
2,test-58,I thought the best way to do that was to trans...,his,238,Schooley,162,False,Ryan,226,True,http://en.wikipedia.org/wiki/Ryan_Cruthers
3,test-1078,Veteran number 8 Imanol Harinordoquy responded...,his,387,Li*vremont,251,True,Harinordoquy,268,False,http://en.wikipedia.org/wiki/History_of_the_Fr...
4,test-1433,"In 1788, as a newly-minted second lieutenant, ...",he,263,Boyen,179,True,von G*nther,241,False,http://en.wikipedia.org/wiki/Hermann_von_Boyen

In [9]:
df_test = pd.concat([df_test_fem, df_test_neu, df_test_masc], ignore_index=True)
df_test.reset_index(drop=True, inplace=True)
test = df_test.sample(frac=1, random_state=42).reset_index(drop=True)

In [10]:
test['ID'] = test['ID'].astype(str).str.split('-').str[1]
test['ID'] = 'test-' + test['ID']

print(len(test))
test.head()

890

,ID,Text,Pronoun,Pronoun-offset,A,A-offset,A-coref,B,B-offset,B-coref,URL
0,test-1370,"After the house was complete, her father joine...",She,258,Otero,196,True,Gloria Estefan Let It Loose Homecoming Concert,210,False,http://en.wikipedia.org/wiki/Melissa_Otero
1,test-1631,"The show introduced the song Hey , Look Me Ove...",them,368,Lucille Ball,247,True,Lucy Goes,660,False,http://en.wikipedia.org/wiki/Wildcat_(musical)
2,test-1732,She became nationally famous following her 192...,She,276,Edith Cummings,199,True,Ruth Dexter,263,False,http://en.wikipedia.org/wiki/Edith_Cummings
3,test-1716,"When his elder brother , John Sydenham of Comb...",Their,332,Margery Poulet,147,True,Queen Elizabeth,314,False,http://en.wikipedia.org/wiki/Humphrey_Sydenham...
4,test-1192,He was the first Pakistani cricketer to be dis...,their,303,Moulana Mufti Sahibdad Khan,266,False,Abdul Aziz,352,False,http://en.wikipedia.org/wiki/Abdul_Kadir_(cric...

In [11]:
df_train = pd.concat([df_train_fem, df_train_neu, df_train_masc], ignore_index=True)
df_train.reset_index(drop=True, inplace=True)
train = df_train.sample(frac=1, random_state=42).reset_index(drop=True)

In [12]:

train['ID'] = train['ID'].astype(str).str.split('-').str[1]
train['ID'] = 'train-' + train['ID']

print(len(train))
train.head()

3564

,ID,Text,Pronoun,Pronoun-offset,A,A-offset,A-coref,B,B-offset,B-coref,URL
0,train-1354,Averell's plan is to ignite a cattle war and p...,his,281,Blaine,249,False,Averell,263,True,http://en.wikipedia.org/wiki/The_Redhead_from_...
1,train-1847,She won the same award in 2003 for ``Anything ...,her,337,Kylie Minogue,145,False,Britney Spears,163,False,http://en.wikipedia.org/wiki/List_of_songs_wri...
2,train-326,He is concerned about the time away from home ...,they,288,Sally,311,True,Polly,324,False,http://en.wikipedia.org/wiki/Shoot_(Mad_Men)
3,train-634,The torture stops when Clayton is about to giv...,their,363,Burke,412,True,Clayton,451,False,http://en.wikipedia.org/wiki/The_Recruit
4,train-296,In an interview conducted with FightLockdown p...,he,645,Villefort,578,False,Dad,640,True,http://en.wikipedia.org/wiki/Danillo_Villefort

In [13]:
# test.to_csv('TEST_balanced_data.csv', index=False)

In [14]:
# train.to_csv('TRAIN_balanced_data.csv', index=False)