In [3]:
import pandas as pd 
df = pd.read_csv('10000.csv') 
df.head()

,ID,Text,Pronoun,Pronoun-offset,A,A-offset,A-coref,B,B-offset,B-coref,URL
0,test-1650,They originally trained as an occupational the...,their,75,Holly Kenyon,57,True,Jane Alison,70,False,http://en.wikipedia.org/wiki/Holly_Kenyon
1,test-176,"Since May 2011 , they have written a biweekly ...",They,50,Postrel,36,True,Sally Satel,47,False,http://en.wikipedia.org/wiki/Virginia_Postrel
2,test-882,They advocated treating offenders like the men...,their,64,Karl Menninger,67,True,Thomas Szasz,73,False,http://en.wikipedia.org/wiki/Karl_Menninger
3,development-279,"At age 17 , Rinker moved to Seattle and worked...",their,57,Rinker,42,False,Bailey,63,True,http://en.wikipedia.org/wiki/Mildred_Bailey
4,development-300,"They wintered in 1836 - 1837 at New Orleans , ...",they,62,Stewart,50,True,Alfred Jacob Miller,57,False,http://en.wikipedia.org/wiki/William_Drummond_...

In [4]:
import spacy

nlp = spacy.load("en_core_web_sm")

def word_offsets_to_char_offsets(text, word_offsets):
    doc = nlp(text)
    char_offsets = []
    current_offset = 0

    for token in doc:
        if token.i in word_offsets:
            start_char_offset = current_offset
            end_char_offset = current_offset + len(token.text)
            char_offsets.append((start_char_offset, end_char_offset))

        current_offset += len(token.text_with_ws)

    return char_offsets

In [133]:
""""
# example: 
text = df.loc[1, 'Text']
word_offsets = [df.loc[1, 'A-offset']]

char_offsets = word_offsets_to_char_offsets(text, word_offsets)
print(char_offsets)

for offset in char_offsets:
    print("Start:", offset[0], "End:", offset[1])
    
print(text[offset[0]:offset[1]])

start_offset = offset[0]
start_offset
"""

[(199, 203)]
Start: 199 End: 203
Jeff

199

In [5]:
new_A_offsets_start = []
new_A_offsets_end = []

for index, row in df.iterrows():
    
    text = df.loc[index, 'Text']
    word_offsets = [df.loc[index, 'A-offset']]

    char_offsets = word_offsets_to_char_offsets(text, word_offsets)
    
    for offset in char_offsets:
        start_offset = offset[0]
        end_offset = offset[1]
        new_A_offsets_start.append(start_offset)
        new_A_offsets_end.append(end_offset)
        
df['A_offset_start'] = new_A_offsets_start
    
    
df['A_offset_end'] = new_A_offsets_end

In [6]:
new_B_offsets_start = []
new_B_offsets_end = []

for index, row in df.iterrows():
    
    text = df.loc[index, 'Text']
    word_offsets = [df.loc[index, 'B-offset']]

    char_offsets = word_offsets_to_char_offsets(text, word_offsets)
    
    for offset in char_offsets:
        start_offset = offset[0]
        end_offset = offset[1]
        new_B_offsets_start.append(start_offset)
        new_B_offsets_end.append(end_offset)
        
df['B_offset_start'] = new_B_offsets_start
    
    
df['B_offset_end'] = new_B_offsets_end

In [7]:
new_pron_offsets_start = []
new_pron_offsets_end = []

for index, row in df.iterrows():
    
    text = df.loc[index, 'Text']
    word_offsets = [df.loc[index, 'Pronoun-offset']]

    char_offsets = word_offsets_to_char_offsets(text, word_offsets)
    
    for offset in char_offsets:
        start_offset = offset[0]
        end_offset = offset[1]
        new_pron_offsets_start.append(start_offset)
        new_pron_offsets_end.append(end_offset)
        
df['PRON_offset_start'] = new_pron_offsets_start
    
    
df['PRON_offset_end'] = new_pron_offsets_end

In [8]:
df.head()

,ID,Text,Pronoun,Pronoun-offset,A,A-offset,A-coref,B,B-offset,B-coref,URL,A_offset_start,A_offset_end,B_offset_start,B_offset_end,PRON_offset_start,PRON_offset_end
0,test-1650,They originally trained as an occupational the...,their,75,Holly Kenyon,57,True,Jane Alison,70,False,http://en.wikipedia.org/wiki/Holly_Kenyon,336,341,410,414,436,441
1,test-176,"Since May 2011 , they have written a biweekly ...",They,50,Postrel,36,True,Sally Satel,47,False,http://en.wikipedia.org/wiki/Virginia_Postrel,206,213,277,282,291,295
2,test-882,They advocated treating offenders like the men...,their,64,Karl Menninger,67,True,Thomas Szasz,73,False,http://en.wikipedia.org/wiki/Karl_Menninger,366,370,399,405,352,357
3,development-279,"At age 17 , Rinker moved to Seattle and worked...",their,57,Rinker,42,False,Bailey,63,True,http://en.wikipedia.org/wiki/Mildred_Bailey,215,221,318,324,280,285
4,development-300,"They wintered in 1836 - 1837 at New Orleans , ...",they,62,Stewart,50,True,Alfred Jacob Miller,57,False,http://en.wikipedia.org/wiki/William_Drummond_...,273,280,313,319,340,344

In [9]:
final_df = df[['ID', 'Text', 'Pronoun', 'PRON_offset_start', 'PRON_offset_end', 'A', 'A_offset_start', 'A_offset_end', 'A-coref', 'B', 'B_offset_start', 'B_offset_end', 'B-coref', 'URL']]

In [10]:
final_df.head()

,ID,Text,Pronoun,PRON_offset_start,PRON_offset_end,A,A_offset_start,A_offset_end,A-coref,B,B_offset_start,B_offset_end,B-coref,URL
0,test-1650,They originally trained as an occupational the...,their,436,441,Holly Kenyon,336,341,True,Jane Alison,410,414,False,http://en.wikipedia.org/wiki/Holly_Kenyon
1,test-176,"Since May 2011 , they have written a biweekly ...",They,291,295,Postrel,206,213,True,Sally Satel,277,282,False,http://en.wikipedia.org/wiki/Virginia_Postrel
2,test-882,They advocated treating offenders like the men...,their,352,357,Karl Menninger,366,370,True,Thomas Szasz,399,405,False,http://en.wikipedia.org/wiki/Karl_Menninger
3,development-279,"At age 17 , Rinker moved to Seattle and worked...",their,280,285,Rinker,215,221,False,Bailey,318,324,True,http://en.wikipedia.org/wiki/Mildred_Bailey
4,development-300,"They wintered in 1836 - 1837 at New Orleans , ...",they,340,344,Stewart,273,280,True,Alfred Jacob Miller,313,319,False,http://en.wikipedia.org/wiki/William_Drummond_...

In [11]:
new_column_names = {'PRON_offset_start': 'Pronoun-offset', 'PRON_offset_end': 'Pronoun-end', 'A_offset_start': 'A-offset', 'A_offset_end':'A-end', 'B_offset_start' : 'B-offset', 'B_offset_end':'B-end'}
final_df.rename(columns=new_column_names, inplace=True)

/var/folders/sg/84w6v9m54ml60m2z_k9s0dh80000gn/T/ipykernel_36739/3384259950.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.rename(columns=new_column_names, inplace=True)

In [12]:
final_df.head()

,ID,Text,Pronoun,Pronoun-offset,Pronoun-end,A,A-offset,A-end,A-coref,B,B-offset,B-end,B-coref,URL
0,test-1650,They originally trained as an occupational the...,their,436,441,Holly Kenyon,336,341,True,Jane Alison,410,414,False,http://en.wikipedia.org/wiki/Holly_Kenyon
1,test-176,"Since May 2011 , they have written a biweekly ...",They,291,295,Postrel,206,213,True,Sally Satel,277,282,False,http://en.wikipedia.org/wiki/Virginia_Postrel
2,test-882,They advocated treating offenders like the men...,their,352,357,Karl Menninger,366,370,True,Thomas Szasz,399,405,False,http://en.wikipedia.org/wiki/Karl_Menninger
3,development-279,"At age 17 , Rinker moved to Seattle and worked...",their,280,285,Rinker,215,221,False,Bailey,318,324,True,http://en.wikipedia.org/wiki/Mildred_Bailey
4,development-300,"They wintered in 1836 - 1837 at New Orleans , ...",they,340,344,Stewart,273,280,True,Alfred Jacob Miller,313,319,False,http://en.wikipedia.org/wiki/William_Drummond_...

In [16]:
i = 4
a1 = final_df.loc[i, 'Pronoun-offset']
a2 = final_df.loc[i, 'Pronoun-end']

text = df.loc[i, 'Text']
print(text[a1:a2])


a1 = final_df.loc[i, 'A-offset']
a2 = final_df.loc[i, 'A-end']

text = df.loc[i, 'Text']
print(text[a1:a2])


a1 = final_df.loc[i, 'B-offset']
a2 = final_df.loc[i, 'B-end']

text = df.loc[i, 'Text']
print(text[a1:a2])

they
Stewart
Alfred

In [17]:
finalfinal_df = final_df[['ID', 'Text', 'Pronoun', 'Pronoun-offset', 'A', 'A-offset', 'A-coref', 'B', 'B-offset', 'B-coref', 'URL']]

In [18]:
finalfinal_df.head()

,ID,Text,Pronoun,Pronoun-offset,A,A-offset,A-coref,B,B-offset,B-coref,URL
0,test-1650,They originally trained as an occupational the...,their,436,Holly Kenyon,336,True,Jane Alison,410,False,http://en.wikipedia.org/wiki/Holly_Kenyon
1,test-176,"Since May 2011 , they have written a biweekly ...",They,291,Postrel,206,True,Sally Satel,277,False,http://en.wikipedia.org/wiki/Virginia_Postrel
2,test-882,They advocated treating offenders like the men...,their,352,Karl Menninger,366,True,Thomas Szasz,399,False,http://en.wikipedia.org/wiki/Karl_Menninger
3,development-279,"At age 17 , Rinker moved to Seattle and worked...",their,280,Rinker,215,False,Bailey,318,True,http://en.wikipedia.org/wiki/Mildred_Bailey
4,development-300,"They wintered in 1836 - 1837 at New Orleans , ...",they,340,Stewart,273,True,Alfred Jacob Miller,313,False,http://en.wikipedia.org/wiki/William_Drummond_...

In [19]:
sample = finalfinal_df.loc[7, 'Text']
sample

"Many action were too dangerous for Li because he has passed down his physical prime despite being a wushu champion . Jet Li also hurt his ankle badly on the set so Hung had to perform a lot of action . Hung was then Li 's stunt double again in the sequel , Once Upon a Time in China II . They were also featured a role as the leader of the White Lotus Sect ."

In [20]:
finalfinal_df.to_csv('30000.csv', index=False)